name: reelmate
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0  # For downloading files
  youtube_explode_dart: ^1.12.0  # For extracting YouTube video links
  path_provider: ^2.1.2  # Updated version for saving files
  permission_handler: ^11.3.1  # Updated version for requesting storage permissions
  fluttertoast: ^8.2.4  # For displaying messages
  cupertino_icons: ^1.0.8
  http: ^0.13.5  # Added http for API calls
  flutter_launcher_icons: ^0.13.1  # Added for app icons
  url_launcher: ^6.1.14
  

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/social.png
    - assets/ashish.jpg  # Ensure this file exists and the path is correct.
    - assets/         # Include all files in the assets folder.

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"  # Replace with your actual icon file
